### ISSUE TITLE
Gcode Hooks 

### ISSUE THREAD

**Issue by ipepe** [probonopd/WirelessPrinting#109]
I think we could make some kind of "hooks" functionality. That would execute particular gcode files in `SDCARD/hooks/hook_name/file.gcode`. We could have hooks like: 
 * `SDCARD/hooks/after_print_finished/00_play_buzzer_finished.gcode`
 * `SDCARD/hooks/after_print_cancelled/00_move_up_and_left.gcode`
 * `SDCARD/hooks/before_print_started/00_something_something.gcode`
 * `SDCARD/hooks/before_print_file_uploaded/00_preheat_bed.gcode`

What do You think about that?

**Comment by ipepe** [comment]
With that functionality we could potentially resolve theese: https://github.com/probonopd/WirelessPrinting/issues/91 https://github.com/probonopd/WirelessPrinting/issues/8

**Comment by probonopd** [comment]
Personally, I don't like the idea that certain files need to be there on the SD card. Makes it too hard to use because the user would have to fiddle around with files on the SD card first.

**Comment by ipepe** [comment]
We could create a button to create default hook files on sdcard. And with "fat" web UI sdcard file management could improve

**Comment by probonopd** [comment]
Also, all functionality must work with SPIFFS only as well.

**Comment by cpeuschel** [comment]
What is with a configuration file like marlin?

**Comment by probonopd** [comment]
I am hesitant since it will increase overall complexity, both in code and in support. For me, the optimal software "just works" and does not need configuration.

**Comment by cpeuschel** [comment]
We can add an page to upload custom GCODE into the SPIFFS?

**Comment by probonopd** [comment]
Don't you think this sort of thing should better be done by the slicer software?

**Comment by cpeuschel** [comment]
I am your opinion. Then we can close this issue, #91 and #8?

**Comment by probonopd** [comment]
Closing for now since this can be done in the slicer, feel free if you think this should be reopened.
