### ISSUE TITLE
Stops printing before the print is finished

### ISSUE THREAD

**Issue by micktol** [probonopd/WirelessPrinting#11]
What is the default speed for the serial port? 
What value of capacitor do you use?

**Comment by probonopd** [comment]
The default speed in the sketch is 115.200 bits/s but you can change it in the sketch in the `Serial.begin(115200);` line.

The exact value of the capacitor shouldn't matter much, I used 100 uF.

**Comment by probonopd** [comment]
@micktol did you get it to work? Most SD shields already include the required capacitor.

**Comment by micktol** [comment]
Yes, I had it working with and without the capacitor, I tried 3 prints but each time it stopped printing before the print was finished!

**Comment by probonopd** [comment]
Can you point me to the file you tried to print? I have printed tens of different models so far, all without issues. How long is the calculated print time (in Cura) for the failed models?

**Comment by micktol** [comment]
I was not printing from cura.
I sliced with simplfiy3d and then uploaded via web page.

**Comment by probonopd** [comment]
In this case, can you point me to the file you tried to print? How long is the calculated print time (in simplfiy3d) for the failed models?

**Comment by micktol** [comment]
Attached is an example, the slicer estimates 13 minutes 
[tube1.gcode.zip](https://github.com/probonopd/WirelessPrinting/files/870657/tube1.gcode.zip)

**Comment by probonopd** [comment]
@micktol that is very strange, I have definitely printed successful prints that were much, much longer (2 hours and more). Currently I have no clue why this is. Could it be that your firmware responds with something else than "ok"? WirelessPrinting only sends the next line if the printer responded with "ok" before.

**Comment by micktol** [comment]
I am using repetier firmware as I have a radds board.

**Comment by probonopd** [comment]
It might have to do with that. Do you have a means to observe the data that is sent by the printer before the print stalls?

**Comment by probonopd** [comment]
I observed the same.

```
echo:Unknown command: ""
ok
echo:Unknown command: ""
ok
echo:Unknown command: ""
ok
echo:Unknown command: ""
ok
echo:Unknown command: ""
ok
```

Turned out that my SD card needed to be reformatted.
Working again now.

**Comment by probonopd** [comment]
@micktol does the problem persist when you use WirelessPrintAsync? It is rewritten almost from scratch using other libraries, and seems to work much better for me.

**Comment by probonopd** [comment]
Can this be closed?

**Comment by probonopd** [comment]
Apparently yes. Feel free to comment if this should be reopened.
