### ISSUE TITLE
Filament change during printing

### ISSUE THREAD

**Issue by ipepe** [probonopd/WirelessPrinting#111]
Is it possible to implement filament change during printing function?

**Comment by probonopd** [comment]
We would need to check whether we have reached a certain Z-height, and then insert custom G-code. This is essentially the same functionality that is needed like for https://github.com/probonopd/WirelessPrinting/issues/91.

**Comment by probonopd** [comment]
Maybe https://www.prusaprinters.org/color-print/ can do the job already?
