### ISSUE TITLE
Connect printer using ESPUSB

### ISSUE THREAD

**Issue by balku** [probonopd/WirelessPrinting#114]
HI, 
do you see a chance to use ESPUSB https://github.com/cnlohr/espusb to connect to a 3D printer instead of RX TX? 
I have a Creality Ender 3 Pro printer with usb and cannot find a possibility to use RX TX.
Regards
Kurt

**Comment by probonopd** [comment]
If https://github.com/cnlohr/espusb/issues/45 ever gets implemented.

**Comment by balku** [comment]
Many thanks for you quick answer.

**Comment by just-jason** [comment]
> HI
> I have a Creality Ender 3 Pro printer with usb and cannot find a possibility to use RX TX.
 
Not one of the easiest boards to work with, but if you want to give it a try...
![CR10E3](https://user-images.githubusercontent.com/45034489/56455986-144e4a80-6366-11e9-9c7a-811933f3d1a4.jpg)

**Comment by just-jason** [comment]
> If cnlohr/espusb#45 ever gets implemented.

Could this help?
https://github.com/tobozo/ESP32-3DPrinter-Bridge

**Comment by probonopd** [comment]
Yes, that could work but at around $33 I think it's way too expensive; for that kind of money you could go with e.g., an Orange Pi Zero.
