### ISSUE TITLE
Convert to a Library

### ISSUE THREAD

**Issue by ayushsharma82** [probonopd/WirelessPrinting#115]
I think, It would be best to convert this into a Library with callback functions and variables accessed from C++ Class like Temperature, Status etc. It would provide a nice and easy interface for plugging in other libraries. More over, It keeps the clutter away from the user.

If we really want to expand this to common 3d printing users ( who have no experience in programming ), then it should not scare them at first.

Please let me know your views too.

**Comment by probonopd** [comment]
Wouldn't that make it much more complicated for _us_? I have never really written a library.

**Comment by ayushsharma82** [comment]
Nope. It would be a lot organised.  Just look at ESP-DASH on how to work with AsyncWebServer in a Class. 

The goal of a library is to provide a simpler interface for users while not creating a roadblock in developing of their own code. Some users might want to add some functions of their own when using this project, it's really hard to do that in a cluttered environment where the project creator only knows 'what goes where'.

**Comment by probonopd** [comment]
It's certainly worse once not even the creator knows anymore 'what goes where'. I am hesitant since I have only basic Arduino language skills (can write sketches and consume libraries), but I am not really a C++ expert.

**Comment by ayushsharma82** [comment]
It's really not that hard. 

```
class WirelessPrinting{
    public:

    private:
};

```

I will create a branch which is converted into a library. We will test this out incase it is better or not.

**Comment by ayushsharma82** [comment]
So i have copy pasted the whole code into a Library ~ Class format. There are 4 ~ 5 errors on compilation, Any help would be appreciated.

https://github.com/ayushsharma82/WirelessPrinting/tree/library

**Comment by GMagician** [comment]
I suggest to create a singleton class, I think that no more than one instance will be ever used

**Comment by ayushsharma82** [comment]
@GMagician  I agree and i have done that by adopting Singleton Pattern 

Used `extern` .
https://github.com/ayushsharma82/WirelessPrinting/blob/library/src/WirelessPrinting.h#L131

**Comment by GMagician** [comment]
@ayushsharma82 you should decvlarte all methods and fields as static...

**Comment by ayushsharma82** [comment]
If possible, Can anybody make me as a collaborator?
 I can make a branch on this repo and all collaborators can contribute in completing it. I am not familiar with Singleton classes, @GMagician contribution will be highly appreciated.

**Comment by ayushsharma82** [comment]
Or @GMagician  , You can clone my `library` branch in this repo.

**Comment by GMagician** [comment]
> Can anybody make me as a collaborator?

I think is up to @probonopd add collaborators.

**Comment by GMagician** [comment]
@ayushsharma82 you may also add a pull request here, using your code, then we can work on it...

**Comment by probonopd** [comment]
I am not sure whether WirelessPrinting, being an application ("sketch") lends itself to being a library.
A library is for use in other sketches. WirelessPrinting is not for use in other sketches, it is a sketch itself.

So before we make things more complicated (to the point that I don't understand it anymore - what is a singleton class?) let's really think about what the pros and cons are.

**Comment by GMagician** [comment]
Singleton class is a class with just one instance and usually without public constructor. Its instance is selfcreated by a method that return always the same instance.
Don't know real pros/cons , I just gave my opinion about how to do it

**Comment by ayushsharma82** [comment]
It will just help us in future to have a clean code base to work with. You have all functions in `WirelessPrinting.h` header file to get a quick overview, and `WirelessPrinting.cpp` with all of them declared. If we don't organize this into a library then, It will be just time consuming for future development where we will have to read the whole .ino file for 'what we have done so far'.

Another Advantage is Distribution, Once we convert this to a library, We can use Arduino Library Manager to distribute to 'masses' (people who don't understand github / programming ).

**Comment by ayushsharma82** [comment]
@probonopd  Can you create a library branch in this base repo? I will create a pull request to that 'library' branch. We can keep the branch open if it works otherwise we will just scrub the idea.

**Comment by probonopd** [comment]
Done:
https://github.com/probonopd/WirelessPrinting/tree/library

**Comment by ayushsharma82** [comment]
@probonopd  Done

**Comment by ayushsharma82** [comment]
@probonopd I think we should stick with ino file only. Even i don't have time nowdays to completely overwrite the whole thing. 

Instead i will work on beautifying or sperating the current code like Marlin.

🙄

**Comment by probonopd** [comment]
@ayushsharma82 please don't split things into may files, personally I find it much harder then. But your help on beautifying the web interface would definitely be most highly appreciated :-) Let's make it a top example for ESP-DASH.

**Comment by ayushsharma82** [comment]
Roger.
I will only add esp-dash to it.

**Comment by TheAssassin** [comment]
Might be useful to use the OctoPi protocol implementation on e.g., a Raspberry Pi Zero or cheap clones as a headless server with low overhead.
