### ISSUE TITLE
OctoPrint always busy 

### ISSUE THREAD

**Issue by SSkull995** [probonopd/WirelessPrinting#119]
Hi! 
I have a problem setting the wemos on my MKS 1.4. I flashed it with the firmware, no problems; I connected it to my wifi and I can connect to the IP on internet (the web GUI). I can also connect with Cura to it. However, as soon as I say "Print with OctoPrint", Cura says that "Octoprint is busy", thus no print can be done. Any suggestions? I connected it to AUX 1 on the MKS. 
Thanks in advance!

**Comment by SSkull995** [comment]
Edit: I can't print from the web GUI as well

**Comment by probonopd** [comment]
Which firmware and version are you running on the MKS?

Are you sure the ESP is communicating properly with the MKS?

Please connect to the ESP using telnet and observe the messages; please post the log here.

**Comment by SSkull995** [comment]
Hi @probonopd, I actually believe that the wemos d1 doesn't talk at all. I connected to the aux 2 pins, like A11/D65 and A12/D66, but I never declared them in the .ino

**Comment by probonopd** [comment]
A11/D65 and A12/D66 are MKS pins, right? You don't need to declare them in the WirelessPrinting `.ino`. You connect the WeMos TX/RX/GND/5V pins to the appropriate counterparts on the MKS, and that should be it.

**Comment by SSkull995** [comment]
Yes they are the pins for the MKS. However, I don't know why, the printer is not accessible

**Comment by SSkull995** [comment]
I just disconnected the wemos rx-tx and the result is the same, busy

**Comment by GMagician** [comment]
You may check what do you get in ipaddr/info? and as already told you @probonopd check telnet
Note that wemos rx must be connected to MKS tx and wemos tx to mks rx...

**Comment by GMagician** [comment]
Also...sure D65 and D66 are used as tx/rx?

**Comment by SSkull995** [comment]
I will try the telnet later, sorry but yesterday I was a bit tired. I checked on the mks board and the tx and rx pins are located where I put the WeMos, very strange. I will check again in a few hours, as soon as I am back from the lab.

**Comment by SSkull995** [comment]
Thanks a lot!

**Comment by SSkull995** [comment]
Ok so, I checked the connection and...... TA DA! I found the problem, I connected the wemos to the wrong pins. Now it works like a charm, no more cables, except for Repetier Host

**Comment by probonopd** [comment]
Glad it is working for you now.

**Comment by SSkull995** [comment]
Hi @probonopd, I have another issue actually. When I send the code, the response is this:
{
  "files": {
    "local": {
      "name": "cached.gco",
      "origin": "local"
    }
  },
  "done": true
}

The printer doesn't even start

**Comment by SSkull995** [comment]
From both Cura and the IP

**Comment by probonopd** [comment]
Can you watch the output of the telnet port?

**Comment by SSkull995** [comment]
I might have figured it out. I will let you know as soon as I check. What is the correct baud rate to upload the sketch? Arduino tells me that there is an error uploading

Kind regards,
Giovanni

**Comment by SSkull995** [comment]
It says that espcomm open failed, maybe because it is connected to the main board?

Kind regards,
Giovanni

**Comment by probonopd** [comment]
Where does it say "espcomm open failed"?

**Comment by SSkull995** [comment]
Ok so I answer via email but nothing arrived. In the Arduino IDE, when I upload the sketch, in the bottom tab, it says uploading and then espcomm_failed

**Comment by probonopd** [comment]
Do not upload to the ESP over USB while the ESP is attached to the printer.

**Comment by probonopd** [comment]
You could use the OTA (over the air update) function, then you would not need the Arduino IDE nor USB...

**Comment by SSkull995** [comment]
got it. I unplugged the esp from the printer and reduced the baud rate

**Comment by SSkull995** [comment]
So now I am sending the code to wemos OTA through Cura, the bed is heating ahah. Will check once again. If I have to modify something, AFAIU I can do it OTA via the update right? What should I use as update?

**Comment by probonopd** [comment]
Enter the IP address that is displayed on your printer's display after powering on into your web browser and go from there :-) you can upload the `.bin` file (e.g., from https://github.com/probonopd/WirelessPrinting/releases/tag/continuous) there.

**Comment by probonopd** [comment]
Is it printing?

**Comment by SSkull995** [comment]
On the Arduino IDE. Pic below

Kind regards,
Giovanni

**Comment by SSkull995** [comment]
Ok it sent the message ahahah. It prints but when I cancel the print, I need to restart everything and clean the cache

**Comment by SSkull995** [comment]
I believe it is normal

**Comment by probonopd** [comment]
Yes. Seems like it is working for you now. What kind of printer are you using?

**Comment by SSkull995** [comment]
Hi sorry! I replied via email but never arrived. I have a CreatBot modified, with MKS Gen 1.4 and some TMCs
