### ISSUE TITLE
List all the dependencies in README.md

### ISSUE THREAD

**Issue by ayushsharma82** [probonopd/WirelessPrinting#122]
I think we should create a list of all required Dependencies with their specific version in README.md

**Comment by probonopd** [comment]
Yes, please add to the ones already in https://github.com/probonopd/WirelessPrinting#building.

**Comment by ayushsharma82** [comment]
I meant creating a markdown list.
( not everybody uses linux )

**Comment by probonopd** [comment]
Hey, there is bash for macOS and Windows too ;-)
I think users can "translate". Let's not maintain the information in three places.

**Comment by ayushsharma82** [comment]
You can consider readthedocs.io

They can be helpful.

**Comment by probonopd** [comment]
You are right, but like everyone else I am short on time ;-/

**Comment by ayushsharma82** [comment]
Understandable...

**Comment by cpeuschel** [comment]
In my opinion, this can be closed, because we have now platformio and the dependencies is managed by platformio.ini
