### ISSUE TITLE
ESP32 baudrate hardcoded at 115200

### ISSUE THREAD

**Issue by joberthel** [probonopd/WirelessPrinting#135]
https://github.com/probonopd/WirelessPrinting/blob/bad8e5166a2f1bbad95a4fb8849b08d1edfc7d3a/ESP8266WirelessPrintAsync/ESP8266WirelessPrintAsync.ino#L437

Looking at the code it looks like the baudrate for the ESP32 is hardcoded at 115200. So it doesn't cycle though the specified rates like the ESP8266 does.

**Comment by probonopd** [comment]
Indeed. Do you think you can send a pull request? Thanks.

**Comment by probonopd** [comment]
https://github.com/probonopd/WirelessPrinting/pull/151
