### ISSUE TITLE
Can this work on a ESP01 module (without SD card) 

### ISSUE THREAD

**Issue by QuitButton** [probonopd/WirelessPrinting#136]
Its not clear from the instuctions here, can this work on a ESP01 module like these https://www.instructables.com/id/Getting-Started-With-the-ESP8266-ESP-01/ ? If so, is it just a matter of flashing something like ESP8266WirelessPrintAsync_d1_mini_bad8e51 ?

**Comment by probonopd** [comment]
Yes.

**Comment by Keltere** [comment]
Hi, sorry but it uses the slicer as a host? When i submit the gcode i can turn off the pc?

**Comment by probonopd** [comment]
WirelessPrinting turns the ESP8266 into a printer host. You can switch off the PC after the gcode has been received by the ESP8266. The ESP8266 will then stream the gcode to the printer line-by-line while it is printing.
