### ISSUE TITLE
Sample print results

### ISSUE THREAD

**Issue by obertr0n** [probonopd/WirelessPrinting#152]
Hello,
Not an issue, but I was curious how the prints are looking when printed from an ESP8266/ESP32 as a 'master'.
Another interesting bit would be what are the printing setting and if there are any infos regarding the printer Rx/Tx buffers occupation percent.

**Comment by probonopd** [comment]
Hello, prints are looking identical to normal printing.
I don't know how to find out buffer occupation.

**Comment by obertr0n** [comment]
great, thank you for your reply.
