### ISSUE TITLE
AI Thinker ESP32-CAM SD init failure

### ISSUE THREAD

**Issue by romandoss** [probonopd/WirelessPrinting#154]
It's have SD slot connected as TTGO T1 but I always have this error:
[E][sd_diskio.cpp:739] sdcard_mount(): f_mount failed 0x(3)
Another simple sketches with same "SPI.begin(14, 2, 15, 13);" work fine.

**Comment by probonopd** [comment]
ESP32-CAM is not supported yet, see https://github.com/probonopd/WirelessPrinting/issues/94. It would be great if you could get it to work. Let's continue the discussion in that ticket.
