### ISSUE TITLE
Include relevant libraries

### ISSUE THREAD

**Issue by jkruiktech** [probonopd/WirelessPrinting#160]
Dont know that you can "comment" so I just made it an issue.

It would be good to have a version that doesn't assume any additional libraries are already installed. Maybe I should put that together in a separate project? (once I have all my dependencies sorted out myself).
Might help some people to get off the ground a bit quicker, especially those who aren't quick at debugging (e.g. me).

Also getting a few errors when compiling. I would have thought it would work straight out of the box but maybe that's unrealistic given the variety of downloaded libraries.

**Comment by probonopd** [comment]
Are you building like this?

```
# Get PlatformIO (the toolchain we use for compiling)
git clone https://github.com/probonopd/WirelessPrinting
cd WirelessPrinting
wget -c https://downloads.egenix.com/python/install-pyrun
bash install-pyrun --python=3.5 pyrun/
pyrun/bin/pip3 install -U platformio==4.2.1

# Build the firmware (it downloads the needed libraries)
pyrun/bin/platformio run
find . -name "*firmware.bin"
```

**Comment by jkruiktech** [comment]
No sorry I hadn't been building using platformIO. That would be the issue, thanks!
