### ISSUE TITLE
SDfat compile error

### ISSUE THREAD

**Issue by wjflier** [probonopd/WirelessPrinting#161]
can't get past this error. " \Documents\Arduino\libraries\SdFat-2.0.4\src/SdFat.h:423:16: error: 'typedef class File32 File' conflicts with a previous declaration"

**Comment by probonopd** [comment]
Probably you are using some different revision of the library than we used?

**Comment by wjflier** [comment]
That's what I thought, tried a couple.  Guess it's hit and miss

**Comment by probonopd** [comment]
Best start with the exact combination of revisions we are using, and then go from there.
The are automatically used by Platformio but also documented here:

https://github.com/probonopd/WirelessPrinting/blob/acaed497142244f7e95d25bc3a13e4a6f1c886a0/platformio.ini#L19-L26

**Comment by wjflier** [comment]
Ok, I'll play with that.  Thanks

**Comment by wjflier** [comment]
No joy,  same error

**Comment by wjflier** [comment]
I changed all LIbs. to no avail.  unfortunately most of them have been updated.  I never got Platformio to work on my pc.  So as of now it seems this ino is a no go.

**Comment by probonopd** [comment]
What IDE are you using? PlatformIO? If not, please retry with it.

**Comment by wjflier** [comment]
Thanks for the reply.  I using Arduino 1.8.9. Tried 1.8.7 too.  Can't get PlatformIO to run on my pc.  Tried several FS.h files.  Looks like #define FS_NO_GLOBALS is not doing it's job.  Probably move to my new pc this weekend. Win10.

**Comment by probonopd** [comment]
OK, we have never tested this on Windows. Best use PlatformIO on a Linux system that supports it.

**Comment by wjflier** [comment]
Will do, thanks.

**Comment by wjflier** [comment]
FYI, flashed with Pyflasher, worked like a charm. next a good HTML interface.
