### ISSUE TITLE
Does not get loaded from Configuration Folder

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#3]
This plugin does not get loaded from the Cura Configuration Folder.

Seems to be caused by Cura 2.4.0, https://github.com/Ultimaker/Cura/issues/1490

As a workaround:

* Download http://software.ultimaker.com/current/Cura-2.4.0.AppImage
* `sudo mount /home/me/Downloads/Cura-2.4.0.AppImage /mnt`
* `sudo cp -r /mnt Cura.AppDir ; sudo chown -R $USER Cura.AppDir`
* Put the `WirelessPrinting` directory into `./Cura.AppDir/usr/bin/plugins/plugins/` (notice _twice_ the name "plugins")

**Comment by fieldOfView** [comment]
I bet you meant Cura 2.4, not Cura 4.0

**Comment by probonopd** [comment]
2.4.0 to be precise :-)

**Comment by probonopd** [comment]
Thanks, updating documentation accordingly.
