### ISSUE TITLE
Uploading from Cura crashes the ESP, uploading from web form works

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#33]
Uploading from Cura 3.2.1 to the same machine (rather than via its web upload form) crashes the ESP. (Strangely, uploading from Cura 2.7.0 now also crashes it; this was working in earlier builds of WirelessPrinting. Regression? 4a7bb16 did not help.)

**Comment by probonopd** [comment]
Using older library versions in https://github.com/probonopd/WirelessPrinting/commit/f1e613d2e4ed53887f13692b47f624a77ea5b42a doesn't seem to help either...

**Comment by probonopd** [comment]
@fieldofview is there a way to dump the HTTP header of the HTTP GCODE upload? Strange thing is, when I use curl or a HTTP form, then my code (or the libraries used by it) does not crash, but when I use Cura, it does. So I'd need to compare the upload requests...

**Comment by fieldOfView** [comment]
> is there a way to dump the HTTP header of the HTTP GCODE upload?

With the shipping plugin: no.
By editing the plugin (python): yes.

You could also use a network sniffer.

**Comment by probonopd** [comment]
With https://github.com/probonopd/WirelessPrinting/pull/52 we don't get crashes anymore, hence closing.
