### ISSUE TITLE
got error after enter the ip address of esp8266 ?

### ISSUE THREAD

**Issue by fred2088** [probonopd/WirelessPrinting#35]
Dear sir,

got error after enter the ip address of esp8266 (found ip from router) instead of upload gcode page ?

File Not Found

URI: /print
Method: GET
Arguments: 0

Thanks a lot

**Comment by probonopd** [comment]
Hi @fred2088 that is strange. How are you trying to print - using one of the slicer applications or entering http://the-ip-address-of-the-printer directly in the browser?

**Comment by probonopd** [comment]
`/print` is implemented for POST requests only, but it seems you issued a GET to it:

https://github.com/probonopd/WirelessPrinting/blob/master/ESP8266WirelessPrintAsync/ESP8266WirelessPrintAsync.ino#L498-L501

**Comment by fred2088** [comment]
File Not Found

URI: /
Method: GET
Arguments: 0

any parameter got the same error

**Comment by fred2088** [comment]
printer is not yet connected, using windows 7

**Comment by probonopd** [comment]
Then it will not work. It needs a printer to be connected because it is querying the printer before starting up.

**Comment by fred2088** [comment]
can show printer is not connected if query fail ?

Thanks

**Comment by probonopd** [comment]
The way it is currently implemented, the name of the printer is queried from the printer before the rest of the sketch even starts up. If getting the name of the printer does not work, then the system doesn't come up fully. I agree there should be better exception handling but currently I have no time to work on it. Pull requests welcome!

**Comment by fred2088** [comment]
which pin i need to connect with mega2560+ramps 1.4 ?

**Comment by probonopd** [comment]
RX, TX, GND, +5V, RESET.

**Comment by fred2088** [comment]
is the baud rate need to set 115200 and serial0 from marlin ?

**Comment by probonopd** [comment]
Yes 115200, for the serial interface you need to set the interface on the printer board to which you physically connect the ESP.

**Comment by probonopd** [comment]
Please try with the latest version. It has baudrate autodetection. Does it work now?
