### ISSUE TITLE
got wemos d1 mini, can have wiring map ?

### ISSUE THREAD

**Issue by fred2088** [probonopd/WirelessPrinting#37]
Dear Sir,

before are using esp8266-01, can't got it work, now buy the same wifi board wemos d1 mini,

is there any wire map for us to follow ?

Thanks

**Comment by probonopd** [comment]
|WeMos D1 mini|3D printer|
|-|-|
|RST|Reset|
|5V|5V|
|G|GND|
|RX|TX|
|TX|RX|

**Comment by fred2088** [comment]
thanks a lot !!! 
finally got it work !!! but must need to connect to my mega2560 first ...
