### ISSUE TITLE
[Question] What happens when print is aborted?

### ISSUE THREAD

**Issue by GMagician** [probonopd/WirelessPrinting#50]
I'm trying to learn code and I find something that I don't understand, when printer is aborted.

Your code looks like:
```c++
        if(shouldCancelPrint == true){
          shouldCancelPrint == false;
          isPrinting = false;
          return;
        }
```

return exit from function and so `gcodeFile.close()` and `statusTimer.attach(statusInterval, askPrinterForStatus)` are never called. Where do these things are restore?

**Comment by probonopd** [comment]
This may be a bug. I don't know whether canceling works. Please test it with a 3D printer.

**Comment by GMagician** [comment]
As soon as I'll have a working system I will
