### ISSUE TITLE
WEMOS + level converter or not ?

### ISSUE THREAD

**Issue by just-jason** [probonopd/WirelessPrinting#54]
In your own setup, are you running the WEMOS with a level converter or not ?

**Comment by probonopd** [comment]
I am not. I am running the WEMOS off 5V supplied by the printer, but connected to the 5V input of the WEMOS which is internally hooked up to a 3.3V voltage regulator, which means the ESP8266 will run off 3.3V. _At least this is how I think this works; without any warranty._

**Comment by just-jason** [comment]
Thanks, it is great to hear, I will try at my own risk.
