### ISSUE TITLE
Implement UM3NetworkPrinting?

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#61]
Sometimes I think we should investigate using UM3NetworkPrinting https://github.com/Ultimaker/Cura/tree/master/plugins/UM3NetworkPrinting/src - but it may be harder to implement since I have no real Ultimaker machine to compare against...

**Comment by fieldOfView** [comment]
> it may be harder to implement

The protocol used is also much more in flux than with OctoPrint.

**Comment by probonopd** [comment]
That's of course another reason not to do it. So closing this idea for now.
