### ISSUE TITLE
Cura does not show temperatures

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#62]
Yay, uploading and printing from Cura 3.5 works for me in 5d4ba19.

Cura does not show the temperatures. The progress indicator shows progress though!

![](https://user-images.githubusercontent.com/2480569/53592733-ccdde600-3b8e-11e9-9c03-f188c8037d89.png)

During heating, getting on telnet:

```
me@host:~$ telnet 192.168.0.27
Trying 192.168.0.27...
Connected to 192.168.0.27.
Escape character is '^]'.
< #TIMEOUT#
> G1 X113.952 Y90.635 E0.11222
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X114.542 Y90.533 E0.13462
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X115.009 Y90.509 E0.15212
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X134.991 Y90.51 E0.8998
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X135.59 Y90.55 E0.92226
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X136.177 Y90.669 E0.94467
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X136.744 Y90.865 E0.96712
< New line but nothing to do with it
```

During printing, getting 

```
  free heap RAM: 35656

> G1 X128.599 Y97.201 E866.00573
< ok

  1541733
  free heap RAM: 35656

> M105
< ok T:198.9 /200.0 B:60.0 /60.0 T0:198.9 /200.0 @:81 B@:72

  1541744
  free heap RAM: 35608

> G0 F7200 X128.599 Y96.901
```

`/api/printer` does not show the correct values:

```
{
  "state": {
    "text": "Printing",
    "flags": {
      "operational": true,
      "paused": false,
      "printing": true,
      "pausing": false,
      "cancelling": false,
      "sdReady": false,
      "error": false,
      "ready": true,
      "closedOrError": false
    }
  },
  "temperature": {
    "tool0": {
      "actual": 0.0,
      "target": 0.0,
      "offset": 0
    },
    "bed": {
      "actual": 0.0,
      "target": 0.0,
      "offset": 0
    }
  },
  "sd": {
    "ready": false
  }
}
```

**Comment by probonopd** [comment]
It seems like `M105` is not being sent to the printer anymore. Hecne we are not getting temperature from the printer anymore.

**Comment by probonopd** [comment]
Probably caused by 

>     * added support to Cap:AUTOREPORT_TEMP (don't send M105 but only M155 on connection established)

in https://github.com/probonopd/WirelessPrinting/pull/52

cc @GMagician

**Comment by probonopd** [comment]
What was wring with sending `M105`? It seemed to have worked reliably.

**Comment by probonopd** [comment]
We are getting

```
> M105
< ok T:198.9 /200.0 B:60.0 /60.0 T0:198.9 /200.0 @:81 B@:72
```

but it is not parsed correctly?

**Comment by chepo92** [comment]
Because my PR fixes it https://github.com/GMagician/WirelessPrinting/pull/9

**Comment by chepo92** [comment]
> 
> 
> We are getting
> 
> ```
> > M105
> < ok T:198.9 /200.0 B:60.0 /60.0 T0:198.9 /200.0 @:81 B@:72
> ```
> 
> but it is not parsed correctly?

I think your printer doesn't have autotemp respones cap enabled, i figured and solved it yesterday. I'll make PR directly to master

**Comment by GMagician** [comment]
It will never be parsed because of ok in front of M105...I'm going to fix it

**Comment by chepo92** [comment]
#67 Fixes it

**Comment by probonopd** [comment]
Thanks @GMagician, 1740455 fixes it for me :+1:
