### ISSUE TITLE
Implement /api/printer/command

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#63]
We now can implement `/api/printer/command` for using the Cura controls.

![](https://user-images.githubusercontent.com/2480569/53594352-9dc97380-3b92-11e9-8e84-b6efb57d3943.png)

**Comment by chepo92** [comment]
When I saw the Lost connection with printer gone I tried tho buttons I realised we haven't implemented it yet. I'll do it, pls assign it to me.

**Comment by GMagician** [comment]
@chepo92 I'm working at json6 and this will come with it.... something is already present but not fully working

**Comment by probonopd** [comment]
Regading json6, are you sure that _all_ the libraries we are using can handle it?

**Comment by GMagician** [comment]
I'm already able to send gcode and pause printer but more test must be done

**Comment by probonopd** [comment]
Thanks @GMagician
