### ISSUE TITLE
Provide a way to print when "Print Immediately" was not selected

### ISSUE THREAD

**Issue by probonopd** [probonopd/WirelessPrinting#71]
Now that we have a "Print Immediately" checkbox we should also provide a way to print when "Print Immediately" was not selected at upload time. Otherwise one cannot do anything with the uploaded GCODE.

**Comment by chepo92** [comment]
maybe in the same root page display the last uploaded file and a print button?

**Comment by probonopd** [comment]
Yes, that would be good.

**Comment by probonopd** [comment]
Instead of adding another endpoint, we could use the one we already have, `/api/job`.

According to http://docs.octoprint.org/en/master/api/job.html, one must send

```
POST /api/job HTTP/1.1
Host: example.com
Content-Type: application/json
X-Api-Key: abcdef...

{
  "command": "start"
}
```

Now, how can we POST the above from a form/by clicking a button in HTML?

Put it in a hidden textarea and pass to server?

**Comment by probonopd** [comment]
Looking at https://stackoverflow.com/a/6418506, 

```
var xmlhttp = new XMLHttpRequest();   // new HttpRequest instance 
xmlhttp.open("POST", "/api/job");
xmlhttp.setRequestHeader("Content-Type", "application/json");
xmlhttp.send(JSON.stringify({command:"start"}));
```
