### ISSUE TITLE
[Question] broken telnet binary send

### ISSUE THREAD

**Issue by GMagician** [probonopd/WirelessPrinting#73]
I was reading some issues and there is one where it is suggested to use port 23 (is not telnet port that one?) to send something.
In "code revamping" now telnet received data is consider text based data and sent like gcode data.

Is something been broken by this?

**Comment by probonopd** [comment]
I am not 100% sure that it was ever working.

**Comment by GMagician** [comment]
but it's better to think at it as a different "send method" or not?
a command send via telnet my broke all command push/pop sequence and desync code

**Comment by probonopd** [comment]
I'd say let's do https://github.com/probonopd/WirelessPrinting/issues/63 for sending commands.
