### ISSUE TITLE
[Question] versioning with travis

### ISSUE THREAD

**Issue by GMagician** [probonopd/WirelessPrinting#81]
New change to update version with travis will prevent local compile to get a valid program

**Comment by probonopd** [comment]
What error are you getting?

**Comment by GMagician** [comment]
XXXVERSIONXXX because of no local travis

**Comment by probonopd** [comment]
Sure, this is the placeholder where the sed command in .travis.yml would put in the git hash. But does it actually prevent from being compiled?

**Comment by GMagician** [comment]
No sorry wrong statement. It compile but cura and html report an invalid version.
Any user can't have a "correct" versioned version this way without local travis

**Comment by probonopd** [comment]
Yes, because we don't know the version when it is compiled locally... we could use a different placeholder though. Ideas?

**Comment by GMagician** [comment]
that may be better than current

**Comment by probonopd** [comment]
Can you check https://transfer.sh/9bOms/ESP8266WirelessPrintAsync_d1_mini_988efa7.bin please?

**Comment by GMagician** [comment]
How can I download it? .. with arduino ide 

N.B. you may also remove `#define VERSION`. It's no longer used

**Comment by probonopd** [comment]
See the README.md for uploading. You can upload using Python.
