### ISSUE TITLE
Discovering printer constantly

### ISSUE THREAD

**Issue by ipepe** [probonopd/WirelessPrinting#97]
I updated to 10dc081 and ESP can't connect with printer. Im getting:
`Last received response: echo:Unknown command: "p�¯å¸‡˛Êò�ò‡òÊò�òÄˇM115"ok`

**Comment by chepo92** [comment]
Same issue but the cause is other than the order, it has to try at least  times with the same baud

**Comment by GMagician** [comment]
I checked code... and maybe with latest change I made two consecutive commands may be used again (that was not possible with first "big" change I've done to let everything works...I thinks that now we can go back adding two M112...

**Comment by chepo92** [comment]
it was broken by #87

**Comment by GMagician** [comment]
Yes! but first test of it was written with no possibility to send 2 messages and not receive one answer...final revision actually can let it work again so I think two M115 may be readded

**Comment by chepo92** [comment]
> 
> 
> Yes! but first test of it was written with no possibility to send 2 messages and not receive one answer...final revision actually can let it work again so I think two M115 may be readded

I don't think that is the better solution, let me add some magic

**Comment by probonopd** [comment]
@ipepe please try https://transfer.sh/10kbVS/ESP8266WirelessPrintAsync_d1_mini_413711c.bin and let us know if resolves this for you. Thanks!

**Comment by chepo92** [comment]
This one should be working https://transfer.sh/a69dO/ESP8266WirelessPrintAsync_d1_mini_1129b07.bin !

**Comment by chepo92** [comment]
@ipepe How did you connect your ender stock board with esp? as far as I know it doesn't have the serial pins to conect (I don't have an ender to try)

**Comment by ipepe** [comment]
@chepo92 https://wiki.ipepe.pl/doku.php?id=ender3:esp3d_wirelessprinting

@probonopd will check in few hours

**Comment by chepo92** [comment]
> @chepo92 https://wiki.ipepe.pl/doku.php?id=ender3:esp3d_wirelessprinting
> 
I imagined that was needed.  
So technicaly it's not stock, some hacking is needed

**Comment by ipepe** [comment]
What's I meant by stock is that its not MKS. To be truly stock it should have stock firmware also.

**Comment by probonopd** [comment]
We should attempt not to be too dependent on the particularities of any individual firmware, if possible.

**Comment by chepo92** [comment]
> We should attempt not to be too dependent on the particularities of any individual firmware, if possible.

I don't see your point, marlin fw is like one of the standart (if not the most used), printer detection wasn't working for it so it wouldn't for any marlin-like fw

**Comment by probonopd** [comment]
I agree.

**Comment by ipepe** [comment]
I flashed 1129b07 and seems to be working. Although it is prone to freezing and slow at responding to requests.
