### ISSUE TITLE
Gcode Timeout

### ISSUE THREAD

**Issue by chepo92** [probonopd/WirelessPrinting#99]
While printing i had a gcode timeout
(In line 292 )
Not critical but can't explain it. 

[GCodetimingOut.txt](https://github.com/probonopd/WirelessPrinting/files/2923448/GCodetimingOut.txt)

**Comment by probonopd** [comment]
Which version of the sketch is this? Looks outdated.

**Comment by GMagician** [comment]
That really seems not an updated version.. there is no more heap status when message is ok and also autotemp parsed is not anymore like this

**Comment by chepo92** [comment]
Yeah my fault, messed that log
